// inspectlet.js - Boots up the inspectlet inspector. Run it in a bookmarklet as javascript:try { inspectlet...
try { inspectlet_createInspector(); } catch { alert("Run the injection script first");};
